Repository Dart-Code/Dart-Code, pull requests merged in 2018-03, with the labels that each got.

#679 Add keybinding ctrl+f5 to flutter.fullRestart command
  package.json
Labels: in debugger, in flutter, is enhancement

#732 Add keybind for Organize Directives
  package.json
Labels: in editor, is enhancement

#733 Add support for flutter profile/release mode
  package.json
  src/debug/flutter_debug_impl.ts
  src/debug/utils.ts
  src/providers/debug_config_provider.ts
Labels: in debugger, in flutter, is enhancement

#725 Fix dupe code actions
  src/providers/fix_code_action_provider.ts
  test/flutter_only/providers/fix_code_action_provider.test.ts
Labels: in editor, is bug fix

#755 Record test results to Amazon S3
  .gitignore
  .travis.yml
  .vscodeignore
  appveyor.yml
  package-lock.json
  package.json
  test/test_all.ts
  test/test_runner.ts
  tool/post_to_chat.ts
Labels: is testing
