Repository Dart-Code/Dart-Code, pull requests merged in 2018-05, with the labels that each got.

#860 Implement conditional breakpoints
  src/debug/dart_debug_impl.ts
  test/dart_only/debug/dart_cli.test.ts
Labels: in debugger, is enhancement

#880 Add an index to map entries for debugger display
  src/debug/dart_debug_impl.ts
Labels: in debugger, is bug fix

#876 Fix static error - Dart 2 semantics
  test/test_projects/hello_world/lib/everything.dart
Labels: is testing

#875 Handle initial thread states other than PauseStart
  src/debug/dart_debug_impl.ts
Labels: in debugger, is non-functional

#899 Track paused state so we don't unpause twice at startup
  src/debug/dart_debug_impl.ts
  test/dart_only/debug/dart_cli.test.ts
Labels: in debugger, is bug fix

#909 Delay sending setLibraryDebuggables until isolate is runnable
  src/debug/dart_debug_impl.ts
Labels: in debugger, is bug fix

#900 Add support for launch emulators
  package.json
  src/flutter/device_manager.ts
  src/flutter/flutter_daemon.ts
  src/providers/debug_config_provider.ts
Labels: in flutter, is enhancement

#921 Change providers to create instances of types rather than returning objects that implement them
  src/providers/assist_code_action_provider.ts
  src/providers/dart_reference_provider.ts
  src/providers/fix_code_action_provider.ts
  src/providers/legacy_dart_workspace_symbol_provider.ts
  src/providers/refactor_code_action_provider.ts
Labels: is non-functional

#940 When terminating tests, abort whole run
  test/test_all.ts
Labels: is testing

#935 Rename windows drive letter handling to normaliseWindowsDriveLetters …
  package.json
  src/config.ts
  src/extension.ts
  src/utils.ts
Labels: is enhancement

#932 Improvements to call stack rendering
  src/debug/dart_debug_impl.ts
Labels: in debugger, is enhancement
