Repository Dart-Code/Dart-Code, pull requests merged in 2019-07, with the labels that each got.

#1841 Switch to fs.realpathSync.native instead of custom code
  package-lock.json
  package.json
  src/extension/extension.ts
  src/shared/utils/fs.ts
Labels: is non-functional

#1856 Remove new keyword on Dart 2.0 >
  src/test/test_projects/flutter_hello_world/example/lib/main.dart
  src/test/test_projects/flutter_hello_world/lib/broken.dart
  src/test/test_projects/flutter_hello_world/lib/main.dart
  src/test/test_projects/flutter_web/broken/lib/main.dart
  src/test/test_projects/hello_world/bin/broken.dart
  src/test/test_projects/hello_world/bin/getters.dart
  src/test/test_projects/hello_world/bin/main.dart
  src/test/test_projects/hello_world/lib/completion.dart
  src/test/test_projects/hello_world/lib/create_method/class_b.dart
  src/test/test_projects/hello_world/lib/everything.dart
  src/test/test_projects/hello_world/lib/go_to_implementation.dart
Labels: is non-functional

#1872 Show related locations in diagnostics
  src/extension/providers/dart_diagnostic_provider.ts
Labels: in editor, is enhancement

#1869 Add errors/stacks to dart:developer logging
  src/extension/debug/dart_debug_impl.ts
Labels: in debugger, is enhancement
