Repository Dart-Code/Dart-Code, pull requests merged in 2020-04, with the labels that each got.

#2330 npm audit fix
  package-lock.json
  package.json
Labels: is non-functional

#2369 Implement re-run last test session
  package.json
  src/extension/commands/debug.ts
  src/extension/extension.ts
  src/extension/providers/debug_config_provider.ts
  src/shared/constants.ts
Labels: in commands, in testing, is enhancement

#2375 Remove the hardcoded repo name from the workflow logic
  .github/workflows/build-and-test.yml
Labels: is non-functional

#2379 Remove Chrome setup from CI
  .github/workflows/build-and-test.yml
Labels: is non-functional

#2402 Wait for main process PIDs when terminating
  src/debug/dart_debug_impl.ts
  src/debug/dart_test_debug_impl.ts
  src/debug/flutter_debug_impl.ts
  src/extension/commands/debug.ts
Labels: in debugger, in flutter, is bug fix
