Repository Dart-Code/Dart-Code, pull requests merged in 2020-03, with the labels that each got.

#2283 Delay processing of events in the debugger to match request responses
  src/debug/dart_debug_protocol.ts
Labels: in debugger, is bug fix

#2325 Update analyzer.ts
  src/extension/analysis/analyzer.ts
Labels: is non-functional

#2311 Add Create Offline Configuration
  package.json
  src/extension/commands/sdk.ts
  src/extension/config.ts
Labels: in commands, in flutter, is enhancement
