Repository Dart-Code/Dart-Code, pull requests merged in 2020-08, with the labels that each got.

#2660 Fix "tasks unexpectedly provided a task of type" error
  package.json
  src/extension/extension.ts
  src/extension/pub/build_runner_task_provider.ts
Labels: in commands, is bug fix

#2725 Adds Flutter: Toggle Brightness command
  package.json
  src/debug/dart_debug_impl.ts
  src/debug/flutter_debug_impl.ts
  src/extension/commands/debug.ts
  src/extension/flutter/vm_service_extensions.ts
  src/shared/enums.ts
Labels: in commands, in flutter, is enhancement

#2731 Add test summaries to Suite and Group nodes
  src/extension/views/test_view.ts
  src/test/dart_debug/debug/dart_test.test.ts
  src/test/flutter_test_debug/debug/flutter_test.test.ts
  src/test/helpers.ts
  src/test/test_projects/hello_world/test/dupe_name_test.dart
  src/test/test_projects/hello_world/test/tree_test.dart
Labels: in testing, is enhancement
