Repository Dart-Code/Dart-Code, pull requests merged in 2021-01, with the labels that each got.

#3046 Update package.json
  package.json
Labels: in docs / website

#3051 Use new Page IDs for DevTools
  media/commands/performance.svg
  package.json
  src/extension/commands/debug.ts
  src/extension/sdk/dev_tools/embedded_view.ts
  src/extension/sdk/dev_tools/manager.ts
  src/shared/capabilities/devtools.ts
  src/shared/constants.ts
  src/shared/interfaces.ts
Labels: in commands, is non-functional

#3090 Adds a Run All Skipped Tests command
  package.json
  src/extension/views/test_view.ts
  src/shared/constants.ts
  src/shared/enums.ts
  src/shared/test/coordindator.ts
  src/shared/test/test_model.ts
  src/shared/utils/test.ts
  src/test/dart_debug/debug/dart_test.test.ts
Labels: in commands, in testing, is enhancement

#3100 Support Debug/Run Failed menu item actions on group nodes
  package.json
  src/extension/views/test_view.ts
  src/shared/constants.ts
Labels: in testing, is enhancement

#3101 Pass --run-skipped when running a test from the test tree/code-lens
  src/extension/commands/test.ts
  src/extension/views/test_view.ts
Labels: in testing, is enhancement

#3087 Extract devtools links from flutter structured errors
  package.json
  src/debug/dart_debug_impl.ts
  src/debug/flutter_debug_impl.ts
  src/extension/commands/debug.ts
  src/extension/config.ts
  src/extension/providers/debug_config_provider.ts
  src/extension/sdk/dev_tools/manager.ts
  src/shared/constants.ts
  src/shared/debug/interfaces.ts
  src/shared/flutter/structured_errors.ts
  src/shared/interfaces.ts
Labels: in commands, in flutter, is enhancement

#3106 Fix typo in Coordindator naming
  src/extension/extension.ts
  src/extension/views/test_view.ts
  src/shared/test/coordinator.ts
  src/shared/vscode/interfaces.ts
  src/test/dart_debug_client.ts
Labels: is non-functional
