Repository Dart-Code/Dart-Code, pull requests merged in 2025-07, with the labels that each got.

#5572 Update background task patterns for build_runner 2.5.0
  package.json
Labels: in tasks

#5615 Support waiting for a VM Service in AutoLaunch
  src/shared/vscode/autolaunch.ts
  src/test/dart/debug/autolaunch.test.ts
Labels: is enhancement, in debugger

#5617 Prompt to reload when Flutter projects are added to a Dart-only workspace
  src/extension/extension.ts
  src/extension/flutter/flutter_project_watcher.ts
  src/shared/utils/cache.ts
  src/shared/vscode/utils.ts
Labels: is enhancement, in flutter
